app = 'c2sp-policy-bot'
primary_region = 'iad'

[metrics]
  port = 8080
  path = "/api/metrics"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
