server:
  address: "0.0.0.0"
  port: 8080
  public_url: https://c2sp-policy-bot.fly.dev

logging:
  text: true
  level: info

github:
  web_url: "https://github.com"
  v3_api_url: "https://api.github.com"
  v4_api_url: "https://api.github.com/graphql"

options:
  policy_path: .github/policy.yml
  shared_repository: ""
