name: Check generated files
on: [push, pull_request]
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-go@v5
        with:
          go-version-file: .github/go.mod
      - run: |
          cd .github
          go generate ./...
          git diff --exit-code
