name: Check generated files
on: [push, pull_request]
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version-file: .github/go.mod
          check-latest: true
      - run: |
          cd .github
          go generate ./...
          git diff --exit-code
