on:
  issues:
    types:
      - opened

jobs:
  notify-new-issue:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.body, 'C2SP/stewards')
    steps:
      - name: Prepare webhook data
        id: prepare
        run: >
          echo 'data={
            "content": "New issue: ${{ github.event.issue.html_url }}"
          }' >> $GITHUB_OUTPUT
      - name: Execute Discord webhook
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: >
          curl
          -X POST
          -H "Content-Type: application/json"
          -H "X-GitHub-Event: ${{ github.event.name }}"
          --data "${{ steps.prepare.outputs.data }}"
          $DISCORD_WEBHOOK
